<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtRol</name>
   <tag></tag>
   <elementGuidId>731ba620-2921-4fab-b6f9-27d83578c210</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@type='4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.sc-iCfMLu.sc-furwcr.blavsA.bZFHy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>e442ccb5-d2aa-4e28-bc47-577b0dcc9be9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>55997adf-b035-4d6c-913b-2a46e3c4514e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-iCfMLu sc-furwcr blavsA bZFHy</value>
      <webElementGuid>994ecc46-69ed-40c2-9098-a899ec776d3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ADMINISTRADOR</value>
      <webElementGuid>e0b5f91c-0b8a-49ce-95a6-7ca53e857ff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;single-spa-application:header&quot;)/div[@class=&quot;app__content&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;header&quot;]/div[@class=&quot;header__perfil&quot;]/div[@class=&quot;perfil__info&quot;]/p[@class=&quot;sc-iCfMLu sc-furwcr blavsA bZFHy&quot;]</value>
      <webElementGuid>7a30b953-90a8-4123-acc4-fc416707c1cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@type='4']</value>
      <webElementGuid>75a9efbf-ad1c-47f1-8477-bdda6f2624ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='single-spa-application:header']/div/div/div/div[3]/div/p[2]</value>
      <webElementGuid>ec9fcf72-1f7c-49f6-9137-5b162c735ad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cerrar sesión'])[1]/preceding::p[1]</value>
      <webElementGuid>ffa938df-c0b6-4101-94c3-9f92a992a686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inicio'])[1]/preceding::p[1]</value>
      <webElementGuid>ca05303a-8678-4680-8a0d-b793f95b87bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ADMINISTRADOR']/parent::*</value>
      <webElementGuid>e3276bb0-99c9-4718-b0bd-b39053179db3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]</value>
      <webElementGuid>2ec61a14-500a-464b-9bbc-8deab197ca4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@type = '4' and (text() = 'ADMINISTRADOR' or . = 'ADMINISTRADOR')]</value>
      <webElementGuid>5cdbf15e-39f4-4b84-9fb2-3ea0bf885721</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
