<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtUserMail</name>
   <tag></tag>
   <elementGuidId>a9cc7175-8b9e-43cc-aeca-f7acb4f3fe0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@type='2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.sc-iCfMLu.sc-furwcr.edjXuQ.bZFHy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>9806f41d-22c9-4c3f-ad09-34b30633d0a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>de50537b-0373-4348-b59f-6b5e6a9e8873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-iCfMLu sc-furwcr edjXuQ bZFHy</value>
      <webElementGuid>da16a760-1cf3-4f3d-86e5-da99859cf4af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>owner.owner@yopmail.com</value>
      <webElementGuid>3a7ae376-c643-42c5-b01f-cc400a61fb23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;single-spa-application:header&quot;)/div[@class=&quot;app__content&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;header&quot;]/div[@class=&quot;header__perfil&quot;]/div[@class=&quot;perfil__info&quot;]/p[@class=&quot;sc-iCfMLu sc-furwcr edjXuQ bZFHy&quot;]</value>
      <webElementGuid>2572e593-77b5-4faa-a7e0-218a52320e61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@type='2']</value>
      <webElementGuid>2d0ec08c-47a4-480e-944b-23ebb0b455f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='single-spa-application:header']/div/div/div/div[3]/div/p</value>
      <webElementGuid>c2d392cb-d7b5-491e-bfd8-433a029ee3c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cerrar sesión'])[1]/preceding::p[2]</value>
      <webElementGuid>512e8285-1f39-4582-afc7-cb44834edc03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inicio'])[1]/preceding::p[2]</value>
      <webElementGuid>aa241b12-cc90-4274-94d0-a3bf49875f6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='owner.owner@yopmail.com']/parent::*</value>
      <webElementGuid>1ee13177-a688-4582-b954-b034ed976260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>e9cbfcd6-21c1-462e-9696-6a975d62f2af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@type = '2' and (text() = 'owner.owner@yopmail.com' or . = 'owner.owner@yopmail.com')]</value>
      <webElementGuid>20255751-3342-402a-9f04-ad198d567b66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
