<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frmMailList</name>
   <tag></tag>
   <elementGuidId>45f0c607-00e6-4de9-9ffa-de490b378147</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ifinbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ifinbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>2b949b9b-8a25-4a32-890c-16653a246d51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>11832ebe-fcfd-488a-84df-c74545f2d234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>bff6fb21-b072-4f19-be1a-668158325c04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>677ab553-a077-495b-b9b8-095d4cf37df5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ifinbox</value>
      <webElementGuid>c3ebf6f8-f14c-47a8-8fd1-7e3834ad7e53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>onloadifinbox()</value>
      <webElementGuid>933b2cd7-1dfd-4ffc-9ca2-fca7e21c1128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ifinbox</value>
      <webElementGuid>2800bf85-e563-4935-9b2d-902bc59e8d03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>state</name>
      <type>Main</type>
      <value>full</value>
      <webElementGuid>1ffc7531-315d-497b-95dd-92b758525e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ifinbox&quot;)</value>
      <webElementGuid>b1ad82af-09bd-4f44-9ba4-d5b72b4a1742</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ifinbox']</value>
      <webElementGuid>51b51cb4-4dc6-4b5d-a9ce-91d854927649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wminboxmain']/iframe</value>
      <webElementGuid>78ad5a5c-38ad-40fa-98ff-75e8e0b42ef4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>e38d080c-42ed-4cdb-8d26-ffd372e82876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'ifinbox' and @id = 'ifinbox']</value>
      <webElementGuid>7ff5293b-e3a2-456e-bab8-547ab0403c67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
