<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtMailSubject</name>
   <tag></tag>
   <elementGuidId>51cc830a-9338-47ac-b8fb-847308164dd4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.lmf</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='e_ZwVjAmR1ZGDkAwVmZQNjAQH2ZGL3Zt==']/button/div/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>61b235ec-80b4-48ff-983a-389f9e212fa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lmf</value>
      <webElementGuid>b57aa25a-9c79-4b93-a159-db6661eee2b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>contacto@prismamp.com</value>
      <webElementGuid>fb96c1e7-30f5-4fc1-a18f-22aef5d9ff36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e_ZwVjAmR1ZGDkAwVmZQNjAQH2ZGL3Zt==&quot;)/button[@class=&quot;lm&quot;]/div[@class=&quot;lmfd&quot;]/span[@class=&quot;lmf&quot;]</value>
      <webElementGuid>b0e197f9-8e24-4e5d-a6a8-baf997ffbd6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/03-YopMail/03-1-YopMail-MailList/frmMailList</value>
      <webElementGuid>83b3ca3e-07e6-45fe-84a9-dbf953d9c442</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='e_ZwVjAmR1ZGDkAwVmZQNjAQH2ZGL3Zt==']/button/div/span[2]</value>
      <webElementGuid>9548c98b-e77a-47c4-ad04-51751fa1fb46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='hoy'])[1]/following::span[2]</value>
      <webElementGuid>db6167ee-61bb-4b14-ad90-7318cf109df4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payway - Recupero de contraseña'])[1]/preceding::span[1]</value>
      <webElementGuid>a3aa07b2-4892-4944-86e6-64cb2815540f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='contacto@prismamp.com']/parent::*</value>
      <webElementGuid>753999e3-1066-42ea-9ef1-f5aa225a8246</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>2915997d-f12f-40f1-b709-7cb14a550752</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'contacto@prismamp.com' or . = 'contacto@prismamp.com')]</value>
      <webElementGuid>bdb36bf1-6e68-4fae-a745-e52423a6b3aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
