<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnComenzar</name>
   <tag></tag>
   <elementGuidId>56b45f25-2ca9-4122-93f4-7a750df17453</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.sc-crHmcD.geLNiP</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c323be05-14ca-4d03-b3db-eee84469d051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>66fad53d-3733-4b62-9134-bc57472d5463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-crHmcD geLNiP</value>
      <webElementGuid>8ad7e489-47cb-4685-83ee-952d9e552e6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Comenzar</value>
      <webElementGuid>ee2ab5e7-e904-41f8-9957-1e40aaf05164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tooltip&quot;)/div[@class=&quot;sc-iWBNLc bpWlHA&quot;]/div[@class=&quot;sc-jvvksu fOuEKP&quot;]/div[@class=&quot;sc-edERGn ilPBzh&quot;]/div[@class=&quot;sc-jlsrNB kmIarA&quot;]/button[@class=&quot;sc-crHmcD geLNiP&quot;]</value>
      <webElementGuid>f8ffba58-b4af-4ad7-b92e-3c2ff389eae6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>a0b6ff75-7846-4f24-bd2f-eebffbd4832d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tooltip']/div/div/div[2]/div[2]/button</value>
      <webElementGuid>2e5954ca-0a00-418c-8271-94c3958f3316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mantenete al día'])[1]/following::button[1]</value>
      <webElementGuid>036734cf-c98b-4a32-838c-3a1845db2e16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::button[1]</value>
      <webElementGuid>59c7b8ff-2bfa-450d-ba33-0d3702773f2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Comenzar']/parent::*</value>
      <webElementGuid>c77cc88c-0bbf-40ae-9308-f7cb70153c84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>5dec250f-82b5-457f-9190-f7fa6ab6c4a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Comenzar' or . = 'Comenzar')]</value>
      <webElementGuid>1b450c90-e9d9-44e5-b86b-57a1911872cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
