<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnSiguiente</name>
   <tag></tag>
   <elementGuidId>a58c5553-d708-489d-a8fa-008b464b595f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//span[@type='2'])[33]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.sc-iCfMLu.crKxsc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3930e559-4f49-46a3-a25b-3fd2d8564415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>ff0599c1-5b4c-4283-802f-1e1e1681245a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-iCfMLu crKxsc</value>
      <webElementGuid>2e025ffe-5668-428b-930b-00ae7debe0e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Siguiente</value>
      <webElementGuid>ba1930b9-613b-4924-addd-6d918a0c1729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ReactModal__Body--open&quot;]/div[@class=&quot;ReactModalPortal&quot;]/div[@class=&quot;ReactModal__Overlay ReactModal__Overlay--after-open&quot;]/div[@class=&quot;ReactModal__Content ReactModal__Content--after-open modal-size-md&quot;]/div[@class=&quot;sc-hJZKUC cEGnLa&quot;]/div[@class=&quot;sc-ewSTlh kvHlky&quot;]/div[@class=&quot;sc-jvvksu fOuEKP&quot;]/div[@class=&quot;sc-edERGn ilPBzh&quot;]/div[@class=&quot;sc-jlsrNB kmIarA&quot;]/div[1]/button[@class=&quot;sc-crHmcD geLNiP&quot;]/span[@class=&quot;sc-iCfMLu crKxsc&quot;]</value>
      <webElementGuid>cd211acb-2a70-4ab7-9d4c-9973e8fab241</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//span[@type='2'])[33]</value>
      <webElementGuid>85997249-906f-40c5-a294-97c903db7664</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Potenciá tu negocio con Payway'])[1]/following::span[1]</value>
      <webElementGuid>e554d7e6-86f5-4583-82f5-d7ac86cb02de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::span[1]</value>
      <webElementGuid>60b9917c-19ac-421d-8bc9-072fa3e49dba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Siguiente']/parent::*</value>
      <webElementGuid>94d1e12a-62b5-4947-96f8-aa11e0b7be90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>bf6847e5-9ded-4561-ab02-c5e6c9c4d28b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@type = '2' and (text() = 'Siguiente' or . = 'Siguiente')]</value>
      <webElementGuid>0f33bb07-9fc6-40d1-bea2-16818e07ed1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
