<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnkOmitir</name>
   <tag></tag>
   <elementGuidId>4eaa2d87-08fc-4370-bff7-95a02e83d973</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//span[@type='4'])[20]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.sc-iCfMLu.uAldr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7d7779ec-c4ef-45b7-ad1b-08028234f82a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>c6c824d6-3836-4795-b6bd-7c4bfd76aa94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-iCfMLu uAldr</value>
      <webElementGuid>09f395cf-8f79-476b-94e8-6a726ad0b71c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Omitir</value>
      <webElementGuid>e37c7e6d-2b93-434d-aeb1-e92ecf255c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ReactModal__Body--open&quot;]/div[@class=&quot;ReactModalPortal&quot;]/div[@class=&quot;ReactModal__Overlay ReactModal__Overlay--after-open&quot;]/div[@class=&quot;ReactModal__Content ReactModal__Content--after-open modal-size-md&quot;]/div[@class=&quot;sc-hJZKUC cEGnLa&quot;]/div[@class=&quot;sc-ewSTlh kvHlky&quot;]/div[@class=&quot;sc-jvvksu fOuEKP&quot;]/div[@class=&quot;sc-edERGn ilPBzh&quot;]/div[@class=&quot;sc-jlsrNB kmIarA&quot;]/div[2]/button[@class=&quot;sc-crHmcD kOGLed&quot;]/span[@class=&quot;sc-iCfMLu uAldr&quot;]</value>
      <webElementGuid>b91753d8-b78f-4f05-931f-4912610a4168</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//span[@type='4'])[20]</value>
      <webElementGuid>97d29c3e-819c-42f0-8fe6-888af7a29482</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Iniciar el tutorial'])[1]/following::span[1]</value>
      <webElementGuid>08265cbb-e4f4-4b22-979a-cbe79061145d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ahora somos Payway'])[1]/following::span[2]</value>
      <webElementGuid>4f2267f1-cd7a-416c-8be4-32b014cc61d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Omitir']/parent::*</value>
      <webElementGuid>21b971cd-68be-4f73-8f4f-b61716f779d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/span</value>
      <webElementGuid>c72e08c1-8bb9-4056-9cf7-751e79ba3341</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@type = '4' and (text() = 'Omitir' or . = 'Omitir')]</value>
      <webElementGuid>5d468d05-f853-454c-be4a-e7b55ec777c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
