<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnIngresar</name>
   <tag></tag>
   <elementGuidId>2f2f1fae-e5ba-4360-8664-bc724c94c08d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='single-spa-application:login']/div/div/div/div[2]/form/div[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.footer__btn</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;single-spa-application:login&quot;)/div[@class=&quot;app__content&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;login&quot;]/div[@class=&quot;sc-ezbkAF dvuZag&quot;]/form[@class=&quot;login__form&quot;]/div[@class=&quot;form__footer&quot;]/div[@class=&quot;footer__btn&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0a15ca1b-9de5-442f-bead-a377416bd79f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>footer__btn</value>
      <webElementGuid>6206b4b3-e5a9-46d7-bbcd-b641fbd9d36c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ingresar</value>
      <webElementGuid>df73adb9-f549-4555-a5a1-a98d6a961f24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;single-spa-application:login&quot;)/div[@class=&quot;app__content&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;login&quot;]/div[@class=&quot;sc-ezbkAF dvuZag&quot;]/form[@class=&quot;login__form&quot;]/div[@class=&quot;form__footer&quot;]/div[@class=&quot;footer__btn&quot;]</value>
      <webElementGuid>7a9498d3-4d10-4571-a411-b55b998b0762</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='single-spa-application:login']/div/div/div/div[2]/form/div[3]/div</value>
      <webElementGuid>98da369d-8841-4486-985b-d869c202e294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Olvidaste tu contraseña?'])[1]/following::div[1]</value>
      <webElementGuid>5149f211-c426-48cb-b455-6df55d91003d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Campo Requerido'])[1]/following::div[3]</value>
      <webElementGuid>ee97633c-b12d-46a1-ac17-2465a3f4c7ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Primera vez que ingresás? Registrate'])[1]/preceding::div[1]</value>
      <webElementGuid>de6801bc-2955-4f0c-8d14-c7733b3dbd26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div</value>
      <webElementGuid>d2e77271-b124-4f8d-bc98-9661027b2d39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Ingresar' or . = 'Ingresar')]</value>
      <webElementGuid>7259d338-4363-40cb-bdae-3f0db5e089cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
