<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnkOlvidastePswd</name>
   <tag></tag>
   <elementGuidId>c793ed8e-c87b-4d97-82ad-84df7ef233a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='single-spa-application:login']/div/div/div/div[2]/form/div[3]/a/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.sc-jrQzAO.vfnIM</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;single-spa-application:login&quot;)/div[@class=&quot;app__content&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;login&quot;]/div[@class=&quot;sc-ezbkAF dvuZag&quot;]/form[@class=&quot;login__form&quot;]/div[@class=&quot;form__footer&quot;]/a[@class=&quot;sc-pVTFL kESsHP&quot;]/div[@class=&quot;sc-jrQzAO vfnIM&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ecb19a95-49f7-4aae-af50-fb8b13ea299c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-jrQzAO vfnIM</value>
      <webElementGuid>f9896887-5edf-4dd7-90b5-6d3539105924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>¿Olvidaste tu contraseña?</value>
      <webElementGuid>0dee09b3-8e70-45f7-9223-9f14cfee0e5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;single-spa-application:login&quot;)/div[@class=&quot;app__content&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;login&quot;]/div[@class=&quot;sc-ezbkAF dvuZag&quot;]/form[@class=&quot;login__form&quot;]/div[@class=&quot;form__footer&quot;]/a[@class=&quot;sc-pVTFL kESsHP&quot;]/div[@class=&quot;sc-jrQzAO vfnIM&quot;]</value>
      <webElementGuid>8612eced-8ac0-4a41-bb3d-a6303eb6e211</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='single-spa-application:login']/div/div/div/div[2]/form/div[3]/a/div</value>
      <webElementGuid>9686fbd8-14e3-4453-ba9d-9485b19a75a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Campo Requerido'])[1]/following::div[2]</value>
      <webElementGuid>884e90a2-fa30-4ba0-abaf-cf2c45642964</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contraseña'])[1]/following::div[4]</value>
      <webElementGuid>baf315c9-177a-4933-9512-602142ece151</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ingresar'])[1]/preceding::div[1]</value>
      <webElementGuid>c9ceaec5-0212-4c4e-807d-983d43198e4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Primera vez que ingresás? Registrate'])[1]/preceding::div[2]</value>
      <webElementGuid>0a41aeb4-fd59-431a-a125-bfaa7b3917dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='¿Olvidaste tu contraseña?']/parent::*</value>
      <webElementGuid>ec52e350-79c9-46fd-a6d0-24725abc70cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div</value>
      <webElementGuid>1e58c8bc-1bca-43fa-b479-47a8e1127798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '¿Olvidaste tu contraseña?' or . = '¿Olvidaste tu contraseña?')]</value>
      <webElementGuid>a3dee598-3194-4466-b670-31161108f5db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
