<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtMail</name>
   <tag></tag>
   <elementGuidId>9c1b023c-28e8-496a-bc96-0be933d502bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;email&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;single-spa-application:login&quot;)/div[@class=&quot;app__content&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;login&quot;]/div[@class=&quot;sc-ezbkAF dvuZag&quot;]/form[@class=&quot;login__form&quot;]/div[@class=&quot;form__body form__body--login&quot;]/div[@class=&quot;body__item&quot;]/div[@class=&quot;sc-fotOHu cZSGXX&quot;]/div[@class=&quot;sc-bkkeKt eXxVta&quot;]/input[@class=&quot;sc-ieecCq dTDiHH&quot;][count(. | //*[@name = 'email' and @placeholder = 'ejemplo@payway.com']) = count(//*[@name = 'email' and @placeholder = 'ejemplo@payway.com'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>166ceaae-2427-4b27-8d95-84487fd5008d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>267c1f7e-0ed8-4e8a-bd96-84fc40d2fe04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f040fd6e-8f6b-494c-99b3-bf47f2b28bb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>ejemplo@payway.com</value>
      <webElementGuid>4a7b6d48-2def-44fa-8b14-7d41cb747e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>a5b63677-60fc-4fb8-b958-1d043a8e4a0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-ieecCq dTDiHH</value>
      <webElementGuid>bb7dfd7e-25cc-4c22-9629-e2de640064b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;single-spa-application:login&quot;)/div[@class=&quot;app__content&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;login&quot;]/div[@class=&quot;sc-ezbkAF dvuZag&quot;]/form[@class=&quot;login__form&quot;]/div[@class=&quot;form__body form__body--login&quot;]/div[@class=&quot;body__item&quot;]/div[@class=&quot;sc-fotOHu cZSGXX&quot;]/div[@class=&quot;sc-bkkeKt eXxVta&quot;]/input[@class=&quot;sc-ieecCq dTDiHH&quot;]</value>
      <webElementGuid>9c54ea5b-3599-4683-a61f-2ef7a7672582</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='email']</value>
      <webElementGuid>f1915e20-5ea1-48dc-ac55-b2142cc9efc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='single-spa-application:login']/div/div/div/div[2]/form/div[2]/div/div/div[2]/input</value>
      <webElementGuid>1b2e89ed-d677-455e-8118-7222726edc07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>8c1d693b-82e4-4bc3-8094-27b8cfff54ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'email' and @type = 'text' and @placeholder = 'ejemplo@payway.com']</value>
      <webElementGuid>0bfae70f-0b09-4c64-81c6-a174251b6c58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
