<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtPassword</name>
   <tag></tag>
   <elementGuidId>cea55af0-9243-4c83-889d-de169d13556a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='pwd']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;pwd&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;single-spa-application:login&quot;)/div[@class=&quot;app__content&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;login&quot;]/div[@class=&quot;sc-ezbkAF dvuZag&quot;]/form[@class=&quot;login__form&quot;]/div[@class=&quot;form__body form__body--login&quot;]/div[@class=&quot;body__item&quot;]/div[@class=&quot;sc-fotOHu cZSGXX&quot;]/div[@class=&quot;sc-bkkeKt eXxVta&quot;]/input[@class=&quot;sc-ieecCq dTDiHH&quot;][count(. | //*[@name = 'pwd']) = count(//*[@name = 'pwd'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b4aa7304-fb3d-4c63-98de-2ff3cd8cdd7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pwd</value>
      <webElementGuid>b8ef6cc3-2c44-44c1-a5cd-7aea1559013f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>cbac1d83-ab37-4e28-9b40-ae8a13cd97ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Escribí acá</value>
      <webElementGuid>1f9d7137-40a4-4c52-9e3a-b13910bf7a25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>557edfd4-bffe-4069-8f86-2eb210f30de7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-ieecCq dTDiHH</value>
      <webElementGuid>16a41547-8c9e-4422-bab0-fe9416b43702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;single-spa-application:login&quot;)/div[@class=&quot;app__content&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;login&quot;]/div[@class=&quot;sc-ezbkAF dvuZag&quot;]/form[@class=&quot;login__form&quot;]/div[@class=&quot;form__body form__body--login&quot;]/div[@class=&quot;body__item&quot;]/div[@class=&quot;sc-fotOHu cZSGXX&quot;]/div[@class=&quot;sc-bkkeKt eXxVta&quot;]/input[@class=&quot;sc-ieecCq dTDiHH&quot;]</value>
      <webElementGuid>7d2cadf5-51e3-4fc3-b1a5-308240e67948</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='pwd']</value>
      <webElementGuid>1de7a006-8b5c-42cd-ab31-7fe4cc2a21fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='single-spa-application:login']/div/div/div/div[2]/form/div[2]/div[2]/div/div[2]/input</value>
      <webElementGuid>bbb8fc1e-b5b2-45df-939c-6d3728d6fa20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/input</value>
      <webElementGuid>89dfe0a2-9e6e-471f-adb6-c60b947edebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'pwd' and @type = 'password' and @placeholder = 'Escribí acá']</value>
      <webElementGuid>b9f40194-caec-4197-b2bd-7603ccf7415a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
